package com.walshe.aimarket.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentChunkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentChunkAllPropertiesEquals(DocumentChunk expected, DocumentChunk actual) {
        assertDocumentChunkAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentChunkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentChunkAllUpdatablePropertiesEquals(DocumentChunk expected, DocumentChunk actual) {
        assertDocumentChunkUpdatableFieldsEquals(expected, actual);
        assertDocumentChunkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentChunkAutoGeneratedPropertiesEquals(DocumentChunk expected, DocumentChunk actual) {
        assertThat(actual)
            .as("Verify DocumentChunk auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentChunkUpdatableFieldsEquals(DocumentChunk expected, DocumentChunk actual) {
        assertThat(actual)
            .as("Verify DocumentChunk relevant properties")
            .satisfies(a -> assertThat(a.getChunkIndex()).as("check chunkIndex").isEqualTo(expected.getChunkIndex()))
            .satisfies(a -> assertThat(a.getChunkText()).as("check chunkText").isEqualTo(expected.getChunkText()))
            .satisfies(a -> assertThat(a.getEmbeddingModel()).as("check embeddingModel").isEqualTo(expected.getEmbeddingModel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentChunkUpdatableRelationshipsEquals(DocumentChunk expected, DocumentChunk actual) {
        assertThat(actual)
            .as("Verify DocumentChunk relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
